### ISSUE TITLE
schema_mismatch validation error, when sending events using the solution API events endpoint

### ISSUE THREAD

**Issue by ebirukov** [awslabs/game-analytics-pipeline#1] opened 2021-05-19 15:32 UTC
When sending events using the
solution API events endpoint, the [additionalProperties](source/services/events-processing/config/event_schema.json)
property in the JSON schema definition  cause validation error
`"validation_errors": [
{
"keyword": "additionalProperties",
"dataPath": "",
"schemaPath": "#/additionalProperties",
"params": {
"additionalProperty": "aws_ga_api_validated_flag"
},
"message": "should NOT have additional properties"
}
]`

because input event has additional fields
`"aws_ga_api_validated_flag": true,
"aws_ga_api_requestId": "..",
"aws_ga_api_requestTimeEpoch": ..,`

**Comment by daniel-aws** [comment] 2021-08-12 19:14
Hi @ebirukov, looking into this and replicating steps. Will update once I have been able to do so.

**Comment by hghodrati** [comment] 2022-01-30 21:24
@daniel-aws I was able to replicate the issue brought up by @ebirukov. It is caused by additional metadata that is set when events are sent via the solution API. These three additional fields do not comply with the event schema definition. I fixed the issue and submitted a Pull Request: https://github.com/awslabs/game-analytics-pipeline/pull/3

**Comment by kylesomers** [comment] 2022-05-13 15:07
Merged [pull request](https://github.com/awslabs/game-analytics-pipeline/commit/10875ed5a9567a856999f7efb09cd7b2538417d3)

**Closed** 2022-05-13 15:06 UTC
